services:
  db:
    image: mysql:5.7
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3311:3306"
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - app-network
  backend:
    image: wichanon17978/backend-api-service:latest
    container_name: backend
    depends_on:
      - db
    restart: always
    working_dir: /app
    command: npm start
    volumes:
      - .:/app
    environment:
      DATABASE_URL: mysql://user:password@db/db
      PORT: 3000
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge